const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[<>&"']/g,c=>({"<":"&lt;",">":"&gt;","&":"&amp;",'"':'&quot;',"'":'&#39;'}[c]));
let profiles=[], currentProfile=null, editingId=null, chosenAvatar='adult-male';
let calCursor=new Date();
const themes=[
 ['light','Hiện đại sáng','linear-gradient(135deg,#f7f4ed,#0f766e)'],
 ['dark-calm','Tối thư giãn','linear-gradient(135deg,#13231f,#49c6b4)'],
 ['oriental','Đông phương','linear-gradient(135deg,#f6efe3,#8c4437)'],
 ['dark-premium','Tối cao cấp','linear-gradient(135deg,#121417,#d0a84d)'],
 ['dark-blue','Tối xanh dịu','linear-gradient(135deg,#0d1d2a,#46b8a9)']
];
const avatarDefs={
 'old-male':['Nam lớn tuổi','#5d86a9','#fff','M'], 'old-female':['Nữ lớn tuổi','#d87883','#fff','F'],
 'adult-male':['Nam trung niên','#347f7a','#263a36','M'], 'adult-female':['Nữ trung niên','#bc6d7d','#4a342f','F'],
 'youth-male':['Nam thiếu niên','#57a35c','#3b3028','M'], 'youth-female':['Nữ thiếu niên','#f08fa4','#3b3028','F']
};
function avatarSvg(code){const [label,shirt,hair,sex]=avatarDefs[code]||avatarDefs['adult-male'];const long=sex==='F';return `<svg class="avatar-svg" viewBox="0 0 100 100" aria-label="${label}"><circle cx="50" cy="50" r="48" fill="var(--surface-2)"/><path d="M20 95c3-25 17-34 30-34s27 9 30 34" fill="${shirt}"/><circle cx="50" cy="43" r="22" fill="#f0c7a5"/><path d="M28 42c0-23 13-31 22-31 14 0 24 10 24 30-8-7-16-10-26-10-8 0-14 3-20 11z" fill="${hair}"/>${long?`<path d="M28 35c-5 13-5 26 1 36l9-9c-5-11-4-19 0-28zM72 35c5 13 5 26-1 36l-9-9c5-11 4-19 0-28z" fill="${hair}"/>`:''}<circle cx="42" cy="44" r="2"/><circle cx="58" cy="44" r="2"/><path d="M44 53c4 3 8 3 12 0" fill="none" stroke="#9d5c4a" stroke-width="2" stroke-linecap="round"/></svg>`}
function getAvatar(id){return localStorage.getItem('avatar:'+id)||'adult-male'}
function setAvatar(id,code){localStorage.setItem('avatar:'+id,code)}
async function api(url,opt={}){
  opt={...opt,headers:{...(opt.headers||{})}};
  const pin=localStorage.getItem('xemngay-family-pin');if(pin)opt.headers['X-Family-Pin']=pin;
  let r=await fetch(url,opt),d;try{d=await r.json()}catch{d={}}
  if(r.status===401&&d.detail==='PIN_REQUIRED'){
    const entered=prompt('Ứng dụng gia đình đang được bảo vệ. Nhập mã PIN:');
    if(!entered)throw new Error('Cần mã PIN để truy cập dữ liệu gia đình.');
    localStorage.setItem('xemngay-family-pin',entered);opt.headers['X-Family-Pin']=entered;
    r=await fetch(url,opt);try{d=await r.json()}catch{d={}}
    if(r.status===401){localStorage.removeItem('xemngay-family-pin');throw new Error('Mã PIN không đúng.');}
  }
  if(!r.ok)throw new Error(d.detail||'Không thể thực hiện.');return d
}
function applySettings(){const theme=localStorage.getItem('xemngay-theme')||'light';const font=localStorage.getItem('xemngay-font')||'normal';document.documentElement.dataset.theme=theme;document.documentElement.dataset.font=font;$('font-size').value=font;renderThemes(theme)}
function renderThemes(selected){$('theme-grid').innerHTML=themes.map(([id,name,sw])=>`<button class="theme ${id===selected?'selected':''}" onclick="chooseTheme('${id}')"><div class="swatch" style="background:${sw}"></div><b>${name}</b></button>`).join('')}
function chooseTheme(id){localStorage.setItem('xemngay-theme',id);applySettings()}
function saveSettings(){localStorage.setItem('xemngay-font',$('font-size').value);applySettings()}
function navTo(name){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$('screen-'+name).classList.add('active');document.querySelectorAll('.nav-btn').forEach(x=>x.classList.toggle('active',x.dataset.nav===name));window.scrollTo(0,0);if(name==='calendar')renderCalendar();if(name==='profile')renderProfiles()}
async function loadStatus(){const s=await api('/api/tinh-trang');$('status-banner').innerHTML=`<div class="notice ${s.cham_diem==='NOT_CALIBRATED'?'':'good'}"><b>Trạng thái V1 hiện tại</b><br>${esc(s.canh_bao)}<br><span class="tag">${s.quy_tac_verified} quy tắc VERIFIED</span> <span class="tag">Hiệp Kỷ: ${s.quy_tac_hiep_ky} rule</span></div>`}
async function loadProfiles(){profiles=await api('/api/ho-so');const saved=localStorage.getItem('xemngay-profile');if(saved&&profiles.some(p=>p.profile_id===saved))currentProfile=saved;else currentProfile=profiles[0]?.profile_id||null;$('profile-select').innerHTML=profiles.length?profiles.map(p=>`<option value="${p.profile_id}" ${p.profile_id===currentProfile?'selected':''}>${esc(p.full_name)}</option>`).join(''):'<option value="">— Chưa có hồ sơ —</option>';$('profile-select').onchange=e=>{currentProfile=e.target.value||null;localStorage.setItem('xemngay-profile',currentProfile||'');updateHomeTitle()};updateHomeTitle();renderProfiles()}
function updateHomeTitle(){const p=profiles.find(x=>x.profile_id===currentProfile);$('home-title').textContent=p?`Hôm nay của ${p.full_name}`:'Chào gia đình'}
function renderProfiles(){if(!$('profile-list'))return;$('profile-list').innerHTML=profiles.length?profiles.map(p=>`<div class="card profile-row">${avatarSvg(getAvatar(p.profile_id))}<div class="grow"><b>${esc(p.full_name)}</b><div class="muted">Sinh ${String(p.birth.day).padStart(2,'0')}/${String(p.birth.month).padStart(2,'0')}/${p.birth.year} · ${String(p.birth.hour).padStart(2,'0')}:${String(p.birth.minute).padStart(2,'0')}</div><div class="muted">${esc(p.birth_place_text)}</div></div><div class="row-actions"><button class="btn secondary small" onclick="editProfile('${p.profile_id}')">Sửa</button><button class="btn danger small" onclick="deleteProfile('${p.profile_id}')">Xóa</button></div></div>`).join(''):'<div class="card muted">Chưa có thành viên. Bấm “Thêm người”.</div>'}
function populateTimezones(){let zones=['Asia/Ho_Chi_Minh','Asia/Bangkok','Asia/Singapore','Asia/Shanghai','Asia/Tokyo','Europe/London','America/New_York','America/Los_Angeles','UTC'];try{if(Intl.supportedValuesOf)zones=Intl.supportedValuesOf('timeZone')}catch{}$('p-timezone').innerHTML=zones.map(z=>`<option value="${z}" ${z==='Asia/Ho_Chi_Minh'?'selected':''}>${z==='Asia/Ho_Chi_Minh'?'Việt Nam - ':''}${z}</option>`).join('')}
function renderAvatarChoices(){const current=chosenAvatar;$('avatar-grid').innerHTML=Object.entries(avatarDefs).map(([id,[label]])=>`<button type="button" class="avatar-option ${id===current?'selected':''}" onclick="chooseAvatar('${id}')">${avatarSvg(id)}<small>${label}</small></button>`).join('')}
function chooseAvatar(code){chosenAvatar=code;renderAvatarChoices()}
function openAddProfile(){editingId=null;chosenAvatar='adult-male';$('profile-form-title').textContent='Thêm người';['p-name','p-date','p-time','p-place'].forEach(id=>$(id).value='');$('p-gender').value='NAM';$('p-timezone').value='Asia/Ho_Chi_Minh';$('profile-error').textContent='';renderAvatarChoices();$('profile-modal').classList.add('open')}
function editProfile(id){const p=profiles.find(x=>x.profile_id===id);if(!p)return;editingId=id;chosenAvatar=getAvatar(id);$('profile-form-title').textContent='Sửa hồ sơ';$('p-name').value=p.full_name;$('p-gender').value=p.gender;$('p-date').value=`${p.birth.year}-${String(p.birth.month).padStart(2,'0')}-${String(p.birth.day).padStart(2,'0')}`;$('p-time').value=`${String(p.birth.hour).padStart(2,'0')}:${String(p.birth.minute).padStart(2,'0')}`;$('p-place').value=p.birth_place_text;$('p-timezone').value=p.timezone_name||'Asia/Ho_Chi_Minh';$('profile-error').textContent='';renderAvatarChoices();$('profile-modal').classList.add('open')}
function closeProfileModal(){$('profile-modal').classList.remove('open')}
async function saveProfile(){try{const d=$('p-date').value,t=$('p-time').value;if(!$('p-name').value.trim()||!d||!t||!$('p-place').value.trim())throw new Error('Hãy nhập đủ tên, ngày giờ sinh và nơi sinh.');const body={full_name:$('p-name').value.trim(),gender:$('p-gender').value,birth_year:+d.slice(0,4),birth_month:+d.slice(5,7),birth_day:+d.slice(8,10),birth_hour:+t.slice(0,2),birth_minute:+t.slice(3,5),birth_place_text:$('p-place').value.trim(),timezone_name:$('p-timezone').value};const url=editingId?'/api/ho-so/'+editingId:'/api/ho-so';const p=await api(url,{method:editingId?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});setAvatar(p.profile_id,chosenAvatar);currentProfile=p.profile_id;localStorage.setItem('xemngay-profile',currentProfile);closeProfileModal();await loadProfiles();navTo('profile')}catch(e){$('profile-error').textContent=e.message}}
async function deleteProfile(id){const p=profiles.find(x=>x.profile_id===id);if(!confirm(`Xóa hồ sơ ${p?.full_name||''}? Dữ liệu sinh của người này sẽ bị xóa khỏi app.`))return;await api('/api/ho-so/'+id,{method:'DELETE'});localStorage.removeItem('avatar:'+id);await loadProfiles()}
function needProfile(){if(!currentProfile){alert('Hãy thêm và chọn một thành viên trước.');return false}return true}
function fusionHtml(deep,includeDay=false){if(!deep)return'';const layers=[['Đại vận',deep.dai_van?.tru||'Chưa xác định'],['Năm',deep.nam?.tru?.vi||'—'],['Tháng',deep.thang?.tru?.vi||'—']];if(includeDay)layers.push(['Ngày',deep.ngay?.tru_ngay||'—']);return `<div class="fusion">${layers.map(([a,b])=>`<div class="layer"><small>${a}</small><b>${esc(b)}</b><span class="tag">chưa đánh giá thuận/nghịch</span></div>`).join('')}</div>`}
async function openQuestion(kind){if(!needProfile())return;navTo('result');$('result-body').innerHTML='<div class="card">Đang tính…</div>';try{if(kind==='long'){const d=await api('/api/toi-dang-o-dau/'+currentProfile);$('result-title').textContent='Vận dài hạn';$('result-body').innerHTML=`<div class="card"><h3>${esc(d.ho_ten)}</h3><div class="fusion"><div class="layer"><small>Đại vận</small><b>${esc(d.dai_van?.tru||'—')}</b><span class="tag">${d.dai_van?`năm ${d.dai_van.nam_thu_may}/10`:'chưa xác định'}</span></div><div class="layer"><small>Năm</small><b>${esc(d.nam_hien_tai.vi)}</b></div><div class="layer"><small>Tháng</small><b>${esc(d.thang_hien_tai.vi)}</b></div><div class="layer"><small>Đánh giá</small><b class="unknown">Chưa đủ căn cứ</b></div></div></div><div class="notice">App đã xác định vị trí thời gian nhưng chưa nói “thuận/xấu” khi thiếu vượng suy, Dụng/Hỷ/Kỵ và các rule liên quan.</div>${d.dai_van?.canh_bao?.length?`<div class="notice danger"><b>Cảnh báo mốc Đại vận</b>${d.dai_van.canh_bao.map(esc).join('<br>')}</div>`:''}`;return}const d=await api((kind==='month'?'/api/thang-nay/':'/api/hom-nay/')+currentProfile);const simple=d.don_gian,deep=d.chuyen_sau;$('result-title').textContent=kind==='month'?'Tháng này của tôi':'Hôm nay thế nào?';$('result-body').innerHTML=`<div class="card"><h3>Hợp lưu ${kind==='month'?'Đại vận → Năm → Tháng':'Đại vận → Năm → Tháng → Ngày'}</h3>${fusionHtml(deep,kind==='today')}<div class="notice"><b>Trạng thái</b>${esc(simple.vi_sao_chua_cham_diem||'Chưa đủ căn cứ để chấm.')}</div></div><div class="card"><h3>Hệ thống đã xác định</h3><ul class="list-clean">${simple.he_thong_biet_gi.map(x=>`<li>✓ ${esc(x)}</li>`).join('')}</ul></div><div class="card"><h3>Chưa đủ căn cứ</h3><ul class="list-clean">${simple.he_thong_chua_biet_gi.map(x=>`<li>• ${esc(x)}</li>`).join('')}</ul></div><button class="btn secondary" onclick="loadWhy()">TẠI SAO? - xem chuyên sâu</button><div id="why-box"></div>`}catch(e){$('result-body').innerHTML=`<div class="notice danger">${esc(e.message)}</div>`}}
async function loadWhy(){if(!needProfile())return;const d=await api('/api/tai-sao/'+currentProfile);$('why-box').innerHTML=`<div class="card"><h3>Truy ngược Rule → Nguồn</h3>${d.truy_nguoc.map(r=>`<div style="padding:10px 0;border-bottom:1px solid var(--border)"><b>${esc(r.rule_id)} - ${esc(r.name_vi)}</b><br><span class="tag">${esc(r.verification_status)}</span> <span class="tag">tin cậy ${esc(r.confidence)}</span><div class="muted">${esc(r.source_title||'Chưa gắn nguồn')}${r.source_location?' · '+esc(r.source_location):''}</div>${r.passage_excerpt?`<pre>${esc(r.passage_excerpt)}</pre>`:''}</div>`).join('')}</div>`}
function localISODate(d=new Date()){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`}
function renderCalendar(){const y=calCursor.getFullYear(),m=calCursor.getMonth();$('cal-title').textContent=`Tháng ${m+1}/${y}`;const first=new Date(y,m,1),start=new Date(y,m,1-first.getDay());const today=localISODate();let html=['CN','T2','T3','T4','T5','T6','T7'].map(x=>`<div class="dow">${x}</div>`).join('');for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const iso=localISODate(d);html+=`<button class="day ${d.getMonth()!==m?'other':''} ${iso===today?'today':''}" onclick="selectCalendarDay('${iso}',this)"><span class="num">${d.getDate()}</span><span class="state">chưa chấm điểm</span></button>`}$('calendar-grid').innerHTML=html}
function moveMonth(n){calCursor=new Date(calCursor.getFullYear(),calCursor.getMonth()+n,1);renderCalendar()}
async function selectCalendarDay(iso,el){document.querySelectorAll('.day').forEach(x=>x.classList.remove('selected'));el.classList.add('selected');if(!needProfile())return;$('calendar-detail').innerHTML='Đang tính…';try{const d=await api('/api/hom-nay/'+currentProfile+'?ngay='+iso);$('calendar-detail').innerHTML=`<h3>${iso}</h3><div class="notice"><b>Chưa chấm tốt/xấu</b>${esc(d.don_gian.vi_sao_chua_cham_diem)}</div>${fusionHtml(d.chuyen_sau,true)}<button class="btn secondary small" onclick="loadCalendarWhy('${iso}')">Tại sao?</button><div id="calendar-why"></div>`}catch(e){$('calendar-detail').innerHTML=`<div class="notice danger">${esc(e.message)}</div>`}}
async function loadCalendarWhy(iso){const d=await api('/api/tai-sao/'+currentProfile+'?ngay='+iso);$('calendar-why').innerHTML=`<ul class="list-clean">${d.truy_nguoc.map(r=>`<li><b>${esc(r.rule_id)}</b> · ${esc(r.name_vi)} · ${esc(r.verification_status)}</li>`).join('')}</ul>`}
async function loadWorkTypes(){const x=await api('/api/loai-viec');$('work-type').innerHTML=x.map(v=>`<option value="${v.code}">${esc(v.ten)}${v.muc_ho_tro==='NO_RULE'?' - chưa có rule Hiệp Kỷ':''}</option>`).join('');const today=localISODate();$('work-from').value=today;$('work-to').value=today}
async function findDates(){if(!needProfile())return;$('work-result').innerHTML='<div class="card">Đang quét…</div>';try{const d=await api(`/api/tim-ngay/${currentProfile}?viec=${encodeURIComponent($('work-type').value)}&tu_ngay=${$('work-from').value}&den_ngay=${$('work-to').value}`);$('work-result').innerHTML=`<div class="notice"><b>Chưa thể xếp hạng</b>${esc(d.ly_do_khong_xep_hang)}</div><div class="card"><h3>Đã quét ${d.so_ngay_da_quet} ngày</h3>${d.cac_ngay.map(x=>`<div style="padding:9px 0;border-bottom:1px solid var(--border)"><b>${x.ngay}</b> · ${esc(x.tru_ngay)}<div class="muted">Quan hệ Can ngày: ${esc(x.quan_he_voi_ban)} · Điểm: chưa chấm</div></div>`).join('')}</div>`}catch(e){$('work-result').innerHTML=`<div class="notice danger">${esc(e.message)}</div>`}}
async function boot(){applySettings();populateTimezones();renderAvatarChoices();await loadStatus();await loadProfiles();await loadWorkTypes();renderCalendar()}
boot().catch(e=>{$('status-banner').innerHTML=`<div class="notice danger"><b>Không khởi động được</b>${esc(e.message)}</div>`});


// ----- PWA / cài lên màn hình chính -----
let deferredInstallPrompt=null;
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;const b=$('install-button');if(b)b.style.display='block';const st=$('install-state');if(st)st.textContent='Thiết bị này có thể cài ứng dụng trực tiếp.'});
window.addEventListener('appinstalled',()=>{deferredInstallPrompt=null;const b=$('install-button');if(b)b.style.display='none';const st=$('install-state');if(st)st.textContent='Ứng dụng đã được cài trên thiết bị.'});
async function installPWA(){if(!deferredInstallPrompt){alert('Nếu dùng iPhone: Safari → Chia sẻ → Thêm vào Màn hình chính. Nếu dùng Android: Chrome → menu ⋮ → Cài ứng dụng.');return}deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null}
function changeFamilyPinLocal(){const v=prompt('Nhập mã PIN gia đình đã đặt trên máy chủ. Để trống để xóa mã đang lưu trên thiết bị:','');if(v===null)return;if(v.trim())localStorage.setItem('xemngay-family-pin',v.trim());else localStorage.removeItem('xemngay-family-pin');alert(v.trim()?'Đã lưu PIN trên thiết bị này.':'Đã xóa PIN khỏi thiết bị này.')}
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('/service-worker.js').catch(()=>{}));}
